[package]
name = "l20n"
version = "0.1.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]

[dependencies]
rustc-serialize = "0.3"
serde = { git = "https://github.com/serde-rs/serde" }
serde_json = { git = "https://github.com/serde-rs/json" }
serde_derive = "0.8.19"
