[package]
name = "l20n"
version = "0.1.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]

[dependencies]
serde = "0.8.19"
serde_json = "0.8.4"
serde_derive = "0.8.19"
void = "1.0.2"
getopts = "0.2.14"
